" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/syntastic'
call vundle#end()

" Syntax
syntax on
filetype plugin on
filetype indent on

" Display
set title
set number                " Affiche le numero des lignes
set ruler                 " Affiche la position actuelle du curseur
set wrap                  " Affiche les lignes trop longues sur plusieurs lignes

set antialias

" Search
set ignorecase            " Ignore la casse lors d'une recherche
set smartcase             " Si une recherche contient une majuscule,
                          " re-active la sensibilite a la casse
set incsearch             " Surligne les resultats de recherche pendant la saisie
set hlsearch              " Surligne les resultats de recherche

" Tabs
set tabstop=2
set shiftwidth=2
set expandtab

set laststatus=2


" Solarized
set t_Co=256
let g:solarized_termtrans=1
let g:solarized_termcolors=256

if has('gui_running')
  set background=light
else
  set background=dark
endif


set background=dark
colorscheme solarized
call togglebg#map("<F5>")

" NERDTree
" autocmd vimenter * NERDTree
" autocmd vimenter * if !argc() | NERDTree | endif
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif


nmap <silent> <F3> :execute 'NERDTreeToggle ' . getcwd()<CR>


" Disable arrows
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

map! jk <Esc>
map! ;; <Esc>

" Use w!! when you've forgotten to open your file as root
cmap w!! w !sudo tee % >/dev/null
