" Pathogen
call pathogen#infect()
syntax on
filetype plugin indent on

" Solarized
set background=dark
colorscheme solarized

" NERDTree
autocmd vimenter * NERDTree
autocmd vimenter * if !argc() | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif


